# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'josephus_interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 110, 301, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_start = QtWidgets.QLabel(self.frame)
        self.label_start.setGeometry(QtCore.QRect(40, 0, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_start.setFont(font)
        self.label_start.setObjectName("label_start")
        self.label_step = QtWidgets.QLabel(self.frame)
        self.label_step.setGeometry(QtCore.QRect(40, 40, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_step.setFont(font)
        self.label_step.setObjectName("label_step")
        self.lineEdit_start = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_start.setGeometry(QtCore.QRect(130, 10, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_start.setFont(font)
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.lineEdit_step = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_step.setGeometry(QtCore.QRect(130, 50, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_step.setFont(font)
        self.lineEdit_step.setText("")
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(160, 20, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 200, 301, 351))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_people = QtWidgets.QLabel(self.frame_2)
        self.label_people.setGeometry(QtCore.QRect(40, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_people.setFont(font)
        self.label_people.setObjectName("label_people")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(40, 50, 201, 271))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.toolButton_file = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_file.setGeometry(QtCore.QRect(160, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.toolButton_file.setFont(font)
        self.toolButton_file.setObjectName("toolButton_file")
        self.toolButton_ok = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_ok.setGeometry(QtCore.QRect(160, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.toolButton_ok.setFont(font)
        self.toolButton_ok.setObjectName("toolButton_ok")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(300, 110, 401, 441))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.toolButton_run = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_run.setGeometry(QtCore.QRect(290, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.toolButton_run.setFont(font)
        self.toolButton_run.setObjectName("toolButton_run")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setGeometry(QtCore.QRect(20, 140, 261, 271))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_showresult = QtWidgets.QLabel(self.frame_3)
        self.label_showresult.setGeometry(QtCore.QRect(90, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_showresult.setFont(font)
        self.label_showresult.setObjectName("label_showresult")
        self.toolButton_quit = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_quit.setGeometry(QtCore.QRect(290, 410, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.toolButton_quit.setFont(font)
        self.toolButton_quit.setObjectName("toolButton_quit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_start.setText(_translate("MainWindow", "START:"))
        self.label_step.setText(_translate("MainWindow", "STEP:"))
        self.label_title.setText(_translate("MainWindow", "Game of Josephus Ring"))
        self.label_people.setText(_translate("MainWindow", "PEOPLE"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolButton_file.setText(_translate("MainWindow", "from file"))
        self.toolButton_ok.setText(_translate("MainWindow", "OK"))
        self.toolButton_run.setText(_translate("MainWindow", "run"))
        self.label_showresult.setText(_translate("MainWindow", "show result"))
        self.toolButton_quit.setText(_translate("MainWindow", "quit"))
